#!/usr/bin/env bash
# Lookup for link in quickmarks/bookmarks/history with `fzfmenu` or `dmenu`

readonly CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}

main() {
  if [ "$#" -eq 0 ]; then
    help
    exit
  fi

  strategy=all

  while [ "$#" -gt 0 ]; do
    case "$1" in
      '-d' | '--domain')
        strategy=domain
        shift
        ;;
      '-c' | '--current')
        strategy=current
        shift
        ;;
      '-t' | '--fzf-terminal')
        shift
        if [ "$#" -gt 0 ]; then
          fzf_terminal="$1"
          shift
        else
          echo "--fzf-terminal requires an argument." >&2
          exit 1
        fi
        ;;
      '-h' | '--help')
        help
        exit
        ;;
      '--')
        shift
        break
        ;;
      *)
        break
        ;;
    esac
  done

  if [ -n "$fzf_terminal" ]; then
    export FZF_TERMINAL="$fzf_terminal"
  fi

  urls=$(history | select_ "$strategy" | menu "$strategy")
  urls=$(sed 's-.*\(https\|http\|file\)://-\1://-' <<< "$urls")

  # If no selection is made, exit (escape pressed, e.g.)
  [[ -z $urls ]] && exit 0

  prefix="$@"
  sed "s/^/$prefix /" <<< "$urls" >> "$QUTE_FIFO"
}

help() {
  cat >&2 << 'EOF'
Usage: qmenu [OPTIONS] [--] [QUTE_COMMAND_PREFIX]

Options:
  -d, --domain        Select domains from history.
  -c, --current       Select current domain URLs from history.
  -t, --fzf-terminal  Set FZF_TERMINAL.
  -h, --help          Show this message and exit.
EOF
}

history() {
  # History
  printf -- '%s\n' "$(sqlite3 -separator ' ' "$QUTE_DATA_DIR/history.sqlite" 'select title, url from CompletionHistory order by last_atime desc')"

  # Quickmarks
  while read -r url; do
    printf -- '%s\n' "$url"
  done < "$QUTE_CONFIG_DIR"/quickmarks

  # Bookmarks
  while read -r url _; do
    printf -- '%s\n' "$url"
  done < "$QUTE_CONFIG_DIR"/bookmarks/urls
}

select_() {
  case "$1" in
    'domain')
      sed 's-.*\(https\|http\|file\)://\([^/]*\).*-\1://\2-' \
        | nl | sort -k 2 | uniq -f 1 | sort -nk 1 \
        | sed 's-\s*[0-9]*\s*--; /qute:\/\//d'
      ;;
    'current')
      grep -F "$(sed 's-\([^/]*\)//\([^/]*\).*-\1//\2-' <<< "$QUTE_URL")"
      ;;
    *)
      cat
      ;;
  esac
}

menu() {
  if type fzfmenu > /dev/null; then
    fzfmenu \
      --ansi \
      --border --border-label " qmenu [$1] " \
      --gap \
      --highlight-line \
      --prompt 'qutebrowser> ' \
      --scheme history \
      --wrap --wrap-sign ' ↳ '
  elif type dmenu > /dev/null; then
    [[ -s "$CONFIG_HOME"/dmenu/font ]] && read -r font < "$CONFIG_HOME"/dmenu/font
    [[ -n $font ]] && opts+=(-fn "$font")
    opts+=(-p qutebrowser)
    dmenu -l 10 "${opts[@]}"
  else
    echo "$(basename "$0") expects either fzfmenu or dmenu to be available." >&2
    exit 1
  fi
}

main "$@"
