#!/usr/bin/env bash
# Lookup for link in quickmarks/bookmarks/history with dmenu

#:bind o spawn --userscript qmenu open
#:bind O spawn --userscript qmenu open -t

readonly CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}

main() {
  if [ "$#" -eq 0 ]; then
    help
    exit
  fi

  strategy=all

  while [ "$#" -gt 0 ]; do
    case "$1" in
      '-d' | '--domain')
        strategy=domain
        shift
        ;;
      '-h' | '--help')
        help
        exit
        ;;
      '--')
        shift
        break
        ;;
      *)
        break
        ;;
    esac
  done

  url=$(history | select_ "$strategy" | menu)
  url=$(sed 's-.*\(https\|http\|file\)://-\1://-' <<< "$url")

  # If no selection is made, exit (escape pressed, e.g.)
  [[ -z $url ]] && exit 0

  echo -n "$@ $url" >> "$QUTE_FIFO"
}

help() {
  cat >&2 << 'EOF'
Usage: qmenu [OPTIONS]

Options:
  -d, --domain  Select domains from history.
  -h, --help    Show this message and exit.
EOF
}

history() {
  # History
  printf -- '%s\n' "$(sqlite3 -separator ' ' "$QUTE_DATA_DIR/history.sqlite" 'select title, url from CompletionHistory order by last_atime desc')"

  # Quickmarks
  while read -r url; do
    printf -- '%s\n' "$url"
  done < "$QUTE_CONFIG_DIR"/quickmarks

  # Bookmarks
  while read -r url _; do
    printf -- '%s\n' "$url"
  done < "$QUTE_CONFIG_DIR"/bookmarks/urls
}

select_() {
  case "$1" in
    'domain')
      sed 's-.*\(https\|http\|file\)://\([^/]*\).*-\1://\2-' \
        | nl | sort -k 2 | uniq -f 1 | sort -nk 1 \
        | sed 's-\s*[0-9]*\s*--; /qute:\/\//d'
      ;;
    *)
      cat
      ;;
  esac
}

menu() {
  [[ -s "$CONFIG_HOME"/dmenu/font ]] && read -r font < "$CONFIG_HOME"/dmenu/font
  [[ -n $font ]] && opts+=(-fn "$font")
  opts+=(-p qutebrowser)
  dmenu -l 10 "${opts[@]}"
}

main "$@"
